# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'GUI_3.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1107, 724)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName("tabWidget")
        self.tab_1 = QtWidgets.QWidget()
        self.tab_1.setObjectName("tab_1")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.tab_1)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.groupBox = QtWidgets.QGroupBox(self.tab_1)
        self.groupBox.setObjectName("groupBox")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.groupBox)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.t1_org_img = QtWidgets.QLabel(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.t1_org_img.sizePolicy().hasHeightForWidth())
        self.t1_org_img.setSizePolicy(sizePolicy)
        self.t1_org_img.setMinimumSize(QtCore.QSize(500, 500))
        self.t1_org_img.setMaximumSize(QtCore.QSize(500, 500))
        font = QtGui.QFont()
        font.setPointSize(50)
        self.t1_org_img.setFont(font)
        self.t1_org_img.setScaledContents(True)
        self.t1_org_img.setAlignment(QtCore.Qt.AlignCenter)
        self.t1_org_img.setObjectName("t1_org_img")
        self.horizontalLayout_6.addWidget(self.t1_org_img)
        self.horizontalLayout_2.addWidget(self.groupBox)
        self.groupBox_2 = QtWidgets.QGroupBox(self.tab_1)
        self.groupBox_2.setObjectName("groupBox_2")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.groupBox_2)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.t1_up_img = QtWidgets.QLabel(self.groupBox_2)
        self.t1_up_img.setMinimumSize(QtCore.QSize(500, 500))
        self.t1_up_img.setMaximumSize(QtCore.QSize(500, 500))
        font = QtGui.QFont()
        font.setPointSize(50)
        self.t1_up_img.setFont(font)
        self.t1_up_img.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.t1_up_img.setScaledContents(True)
        self.t1_up_img.setAlignment(QtCore.Qt.AlignCenter)
        self.t1_up_img.setObjectName("t1_up_img")
        self.horizontalLayout_7.addWidget(self.t1_up_img)
        self.horizontalLayout_2.addWidget(self.groupBox_2)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.frame = QtWidgets.QFrame(self.tab_1)
        self.frame.setMaximumSize(QtCore.QSize(16777215, 55))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.t1_msg = QtWidgets.QLabel(self.frame)
        self.t1_msg.setMaximumSize(QtCore.QSize(16777215, 50))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.t1_msg.setFont(font)
        self.t1_msg.setText("")
        self.t1_msg.setObjectName("t1_msg")
        self.horizontalLayout_3.addWidget(self.t1_msg)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem1)
        self.t1_pb_load = QtWidgets.QPushButton(self.frame)
        self.t1_pb_load.setMinimumSize(QtCore.QSize(100, 0))
        self.t1_pb_load.setMaximumSize(QtCore.QSize(100, 16777215))
        self.t1_pb_load.setStyleSheet("QPushButton {\n"
"    padding: 5px;\n"
"    border-radius: 5px;\n"
"    background: rgb(0, 85, 255);\n"
"    color: white;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background: rgb(0, 85, 255, 220);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background: rgb(0, 85, 255, 200);\n"
"}\n"
"\n"
"")
        self.t1_pb_load.setObjectName("t1_pb_load")
        self.horizontalLayout_3.addWidget(self.t1_pb_load)
        self.t1_pb_check = QtWidgets.QPushButton(self.frame)
        self.t1_pb_check.setMinimumSize(QtCore.QSize(100, 0))
        self.t1_pb_check.setMaximumSize(QtCore.QSize(100, 16777215))
        self.t1_pb_check.setStyleSheet("QPushButton {\n"
"    padding: 5px;\n"
"    border-radius: 5px;\n"
"    background: rgb(0, 85, 255);\n"
"    color: white;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background: rgb(0, 85, 255, 220);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background: rgb(0, 85, 255, 200);\n"
"}\n"
"\n"
"")
        self.t1_pb_check.setObjectName("t1_pb_check")
        self.horizontalLayout_3.addWidget(self.t1_pb_check)
        self.verticalLayout.addWidget(self.frame)
        self.tabWidget.addTab(self.tab_1, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.tab_2)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.groupBox_3 = QtWidgets.QGroupBox(self.tab_2)
        self.groupBox_3.setFlat(False)
        self.groupBox_3.setCheckable(False)
        self.groupBox_3.setObjectName("groupBox_3")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.groupBox_3)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.t2_up_img = QtWidgets.QLabel(self.groupBox_3)
        font = QtGui.QFont()
        font.setPointSize(50)
        self.t2_up_img.setFont(font)
        self.t2_up_img.setAlignment(QtCore.Qt.AlignCenter)
        self.t2_up_img.setObjectName("t2_up_img")
        self.horizontalLayout_5.addWidget(self.t2_up_img)
        self.verticalLayout_2.addWidget(self.groupBox_3)
        self.frame_2 = QtWidgets.QFrame(self.tab_2)
        self.frame_2.setMaximumSize(QtCore.QSize(16777215, 50))
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.frame_2)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem2)
        self.t2_pb_load = QtWidgets.QPushButton(self.frame_2)
        self.t2_pb_load.setMinimumSize(QtCore.QSize(100, 0))
        self.t2_pb_load.setStyleSheet("QPushButton {\n"
"    padding: 5px;\n"
"    border-radius: 5px;\n"
"    background: rgb(0, 85, 255);\n"
"    color: white;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background: rgb(0, 85, 255, 220);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background: rgb(0, 85, 255, 200);\n"
"}\n"
"\n"
"")
        self.t2_pb_load.setObjectName("t2_pb_load")
        self.horizontalLayout_4.addWidget(self.t2_pb_load)
        self.t2_pb_match = QtWidgets.QPushButton(self.frame_2)
        self.t2_pb_match.setMinimumSize(QtCore.QSize(100, 0))
        self.t2_pb_match.setStyleSheet("QPushButton {\n"
"    padding: 5px;\n"
"    border-radius: 5px;\n"
"    background: rgb(0, 85, 255);\n"
"    color: white;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background: rgb(0, 85, 255, 220);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background: rgb(0, 85, 255, 200);\n"
"}\n"
"\n"
"")
        self.t2_pb_match.setObjectName("t2_pb_match")
        self.horizontalLayout_4.addWidget(self.t2_pb_match)
        self.verticalLayout_2.addWidget(self.frame_2)
        self.tabWidget.addTab(self.tab_2, "")
        self.horizontalLayout.addWidget(self.tabWidget)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1107, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.groupBox.setTitle(_translate("MainWindow", "Original Image"))
        self.t1_org_img.setText(_translate("MainWindow", "🖼️"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Uploaded Image"))
        self.t1_up_img.setText(_translate("MainWindow", "🖼️"))
        self.t1_pb_load.setText(_translate("MainWindow", "Load Image"))
        self.t1_pb_check.setText(_translate("MainWindow", "Check"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_1), _translate("MainWindow", "Verification"))
        self.groupBox_3.setTitle(_translate("MainWindow", "Uploaded Image"))
        self.t2_up_img.setText(_translate("MainWindow", "🖼️"))
        self.t2_pb_load.setText(_translate("MainWindow", "Load Image"))
        self.t2_pb_match.setText(_translate("MainWindow", "Match"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Recognition"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
